### ISSUE TITLE
Пытаюсь запустить на Electron,  Cannot find module

### ISSUE THREAD

**Issue by muaddip01** [farafonov-alexey/node-atol-wrapper#11]
Добрый день, пытаюсь запустить на Electron, выдает ошибку:

(node:36188) UnhandledPromiseRejectionWarning: Error: Cannot find module 'C:\git\cashreg\dist\main\package.json'
    at webpackEmptyContext (C:\git\cashreg\dist\main\main.js:78275:10)
    at Object../node_modules/node-atol-wrapper/node_modules/node-pre-gyp/lib/pre-binding.js.exports.find (C:\git\cashreg\dist\main\main.js:79149:123)
    at Object../node_modules/node-atol-wrapper/bindings.js (C:\git\cashreg\dist\main\main.js:65361:29)
    at __webpack_require__ (C:\git\cashreg\dist\main\main.js:20:30)
    at Object../app/electron/main.ts (C:\git\cashreg\dist\main\main.js:1111:21)
    at __webpack_require__ (C:\git\cashreg\dist\main\main.js:20:30)
    at C:\git\cashreg\dist\main\main.js:1091:65
    at processTicksAndRejections (internal/process/task_queues.js:85:5)

При размещении в другом модуле:

[00:03:04.910]   INFO    Electron main process is restarting...
[00:03:06.551]  SUCCESS  Electron main process has restarted.
[00:03:06.676]   INFO    null
[00:03:07.043]   INFO    App threw an error during load

[00:03:07.068]   INFO    Error: package.json does not exist at C:\git\cashreg\dist\main\package.json
    at Object../node_modules/node-atol-wrapper/node_modules/node-pre-gyp/lib/pre-binding.js.exports.find (C:\git\cashreg\dist\main\main.js:79147:15)
    at Object../node_modules/node-atol-wrapper/bindings.js (C:\git\cashreg\dist\main\main.js:65361:29)
    at __webpack_require__ (C:\git\cashreg\dist\main\main.js:20:30)
    at Object../app/core/api/request.ts (C:\git\cashreg\dist\main\main.js:227:21)
    at __webpack_require__ (C:\git\cashreg\dist\main\main.js:20:30)
    at Object../app/core/api/index.ts (C:\git\cashreg\dist\main\main.js:207:22)
    at __webpack_require__ (C:\git\cashreg\dist\main\main.js:20:30)
    at Object../app/core/main.init.ts (C:\git\cashreg\dist\main\main.js:310:34)
    at __webpack_require__ (C:\git\cashreg\dist\main\main.js:20:30)
    at Object../app/electron/index.ts (C:\git\cashreg\dist\main\main.js:1089:21)

**Comment by farafonov-alexey** [comment]
Я думаю проблема связана с подключением пакета к вашему electron приложению, видно, что он пытается найти package.json в папке dist похоже чтобы определить путь до бинарного файла модуля. Однако искать в этой папке он не должен. Попробуйте следующее:
1) запустить этот пакет отдельно, склонировав репозиторий и - npm install && npm start
2) подключить к минимальному electron приложению только этот пакет, и по аналогии с index.js   использовать его, обратите внимание на #2

**Comment by muaddip01** [comment]
У меня довольно сложное приложение, много компонентов задействовано, я так понимаю проблема в webpack, пока так побороть и не получилось :(
