### ISSUE TITLE
Не удается поставить пакет в  Windows 10 (x64)

### ISSUE THREAD

**Issue by squalsoft** [farafonov-alexey/node-atol-wrapper#3]
При npm install следующая ошибка компиляции:

C:\KassMaster\node_modules\node-atol-wrapper>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  Copying C:\KassMaster\node_modules\node-atol-wrapper/src/win-x64/fptr10.dll to C:\KassMaster\node_modul
  es\node-atol-wrapper\build\Release\\fptr10.dll
          1 file(s) copied.
  Copying C:\KassMaster\node_modules\node-atol-wrapper/src/win-x64/fptr10.lib to C:\KassMaster\node_modul
  es\node-atol-wrapper\build\Release\\fptr10.lib
          1 file(s) copied.
  Copying C:\KassMaster\node_modules\node-atol-wrapper/src/win-x64/msvcp140.dll to C:\KassMaster\node_mod
  ules\node-atol-wrapper\build\Release\\msvcp140.dll
          1 file(s) copied.
  index.cc
  fptr10.cc
c:\kassmaster\node_modules\nan\nan_converters_43_inl.h(22): warning C4996: 'v8::Value::ToBoolean': was de
clared deprecated (compiling source file ..\src\index.cc) [C:\KassMaster\node_modules\node-atol-wrapper\b
uild\node_atol_wrapper.vcxproj]
  c:\users\didiandmalish\.node-gyp\12.2.0\include\node\v8.h(2523): note: see declaration of 'v8::Value::T
  oBoolean' (compiling source file ..\src\index.cc)
c:\kassmaster\node_modules\nan\nan_converters_43_inl.h(40): warning C4996: 'v8::Value::BooleanValue': was
 declared deprecated (compiling source file ..\src\index.cc) [C:\KassMaster\node_modules\node-atol-wrappe
r\build\node_atol_wrapper.vcxproj]
  c:\users\didiandmalish\.node-gyp\12.2.0\include\node\v8.h(2561): note: see declaration of 'v8::Value::B
  ooleanValue' (compiling source file ..\src\index.cc)
c:\kassmaster\node_modules\nan\nan_converters_43_inl.h(22): warning C4996: 'v8::Value::ToBoolean': was de
clared deprecated (compiling source file ..\src\fptr10.cc) [C:\KassMaster\node_modules\node-atol-wrapper\
build\node_atol_wrapper.vcxproj]
c:\kassmaster\node_modules\nan\nan_implementation_12_inl.h(103): error C2664: 'v8::MaybeLocal<v8::Functio
n> v8::Function::New(v8::Local<v8::Context>,v8::FunctionCallback,v8::Local<v8::Value>,int,v8::Constructor
Behavior,v8::SideEffectType)': cannot convert argument 1 from 'v8::Isolate *' to 'v8::Local<v8::Context>'
 (compiling source file ..\src\index.cc) [C:\KassMaster\node_modules\node-atol-wrapper\build\node_atol_wr
apper.vcxproj]
  c:\users\didiandmalish\.node-gyp\12.2.0\include\node\v8.h(2523): note: see declaration of 'v8::Value::T
  oBoolean' (compiling source file ..\src\fptr10.cc)c:\kassmaster\node_modules\nan\nan_implementation_12_
  inl.h(105): note: No constructor could take the source type, or constructor overload resolution was amb
  iguous (compiling source file ..\src\index.cc)

c:\kassmaster\node_modules\nan\nan_implementation_12_inl.h(337): error C2660: 'v8::StringObject::New': fu
nction does not take 1 arguments (compiling source file ..\src\index.cc) [C:\KassMaster\node_modules\node
-atol-wrapper\build\node_atol_wrapper.vcxproj]
  c:\users\didiandmalish\.node-gyp\12.2.0\include\node\v8.h(5380): note: see declaration of 'v8::StringOb
  ject::New' (compiling source file ..\src\index.cc)
c:\kassmaster\node_modules\nan\nan_converters_43_inl.h(40): warning C4996: 'v8::Value::BooleanValue': was
 declared deprecated (compiling source file ..\src\fptr10.cc) [C:\KassMaster\node_modules\node-atol-wrapp
er\build\node_atol_wrapper.vcxproj]
  c:\users\didiandmalish\.node-gyp\12.2.0\include\node\v8.h(2561): note: see declaration of 'v8::Value::B
  ooleanValue' (compiling source file ..\src\fptr10.cc)
c:\kassmaster\node_modules\nan\nan_implementation_12_inl.h(337): error C2059: syntax error: ')' (compilin
g source file ..\src\index.cc) [C:\KassMaster\node_modules\node-atol-wrapper\build\node_atol_wrapper.vcxp
roj]
c:\kassmaster\node_modules\nan\nan_implementation_12_inl.h(103): error C2664: 'v8::MaybeLocal<v8::Functio
n> v8::Function::New(v8::Local<v8::Context>,v8::FunctionCallback,v8::Local<v8::Value>,int,v8::Constructor
Behavior,v8::SideEffectType)': cannot convert argument 1 from 'v8::Isolate *' to 'v8::Local<v8::Context>'
 (compiling source file ..\src\fptr10.cc) [C:\KassMaster\node_modules\node-atol-wrapper\build\node_atol_w
rapper.vcxproj]
  c:\kassmaster\node_modules\nan\nan_implementation_12_inl.h(105): note: No constructor could take the so
  urce type, or constructor overload resolution was ambiguous (compiling source file ..\src\fptr10.cc)
c:\kassmaster\node_modules\nan\nan_implementation_12_inl.h(337): error C2660: 'v8::StringObject::New': fu
nction does not take 1 arguments (compiling source file ..\src\fptr10.cc) [C:\KassMaster\node_modules\nod
e-atol-wrapper\build\node_atol_wrapper.vcxproj]
  c:\users\didiandmalish\.node-gyp\12.2.0\include\node\v8.h(5380): note: see declaration of 'v8::StringOb
  ject::New' (compiling source file ..\src\fptr10.cc)
c:\kassmaster\node_modules\nan\nan_implementation_12_inl.h(337): error C2059: syntax error: ')' (compilin
g source file ..\src\fptr10.cc) [C:\KassMaster\node_modules\node-atol-wrapper\build\node_atol_wrapper.vcx
proj]
c:\kassmaster\node_modules\nan\nan.h(1034): error C2661: 'v8::Value::ToString': no overloaded function ta
kes 0 arguments (compiling source file ..\src\index.cc) [C:\KassMaster\node_modules\node-atol-wrapper\bui
ld\node_atol_wrapper.vcxproj]
c:\kassmaster\node_modules\nan\nan.h(1044): error C2664: 'int v8::String::WriteUtf8(v8::Isolate *,char *,
int,int *,int) const': cannot convert argument 1 from 'char *' to 'v8::Isolate *' (compiling source file 
..\src\index.cc) [C:\KassMaster\node_modules\node-atol-wrapper\build\node_atol_wrapper.vcxproj]
  c:\kassmaster\node_modules\nan\nan.h(1044): note: Types pointed to are unrelated; conversion requires r
  einterpret_cast, C-style cast or function-style cast (compiling source file ..\src\index.cc)
c:\kassmaster\node_modules\nan\nan.h(1034): error C2661: 'v8::Value::ToString': no overloaded function ta
kes 0 arguments (compiling source file ..\src\fptr10.cc) [C:\KassMaster\node_modules\node-atol-wrapper\bu
ild\node_atol_wrapper.vcxproj]
c:\kassmaster\node_modules\nan\nan.h(1818): warning C4996: 'v8::Object::Set': was declared deprecated (co
mpiling source file ..\src\index.cc) [C:\KassMaster\node_modules\node-atol-wrapper\build\node_atol_wrappe
r.vcxproj]
  c:\users\didiandmalish\.node-gyp\12.2.0\include\node\v8.h(3358): note: see declaration of 'v8::Object::
  Set' (compiling source file ..\src\index.cc)
c:\kassmaster\node_modules\nan\nan.h(1044): error C2664: 'int v8::String::WriteUtf8(v8::Isolate *,char *,
int,int *,int) const': cannot convert argument 1 from 'char *' to 'v8::Isolate *' (compiling source file 
..\src\fptr10.cc) [C:\KassMaster\node_modules\node-atol-wrapper\build\node_atol_wrapper.vcxproj]
  c:\kassmaster\node_modules\nan\nan.h(1044): note: Types pointed to are unrelated; conversion requires r
  einterpret_cast, C-style cast or function-style cast (compiling source file ..\src\fptr10.cc)
c:\kassmaster\node_modules\nan\nan.h(1824): warning C4996: 'v8::Object::Set': was declared deprecated (co
mpiling source file ..\src\index.cc) [C:\KassMaster\node_modules\node-atol-wrapper\build\node_atol_wrappe
r.vcxproj]
  c:\users\didiandmalish\.node-gyp\12.2.0\include\node\v8.h(3358): note: see declaration of 'v8::Object::
  Set' (compiling source file ..\src\index.cc)
c:\kassmaster\node_modules\nan\nan.h(1830): warning C4996: 'v8::Object::Set': was declared deprecated (co
mpiling source file ..\src\index.cc) [C:\KassMaster\node_modules\node-atol-wrapper\build\node_atol_wrappe
r.vcxproj]
  c:\users\didiandmalish\.node-gyp\12.2.0\include\node\v8.h(3367): note: see declaration of 'v8::Object::
  Set' (compiling source file ..\src\index.cc)
c:\kassmaster\node_modules\nan\nan.h(1836): warning C4996: 'v8::Object::Get': was declared deprecated (co
mpiling source file ..\src\index.cc) [C:\KassMaster\node_modules\node-atol-wrapper\build\node_atol_wrappe
r.vcxproj]
  c:\users\didiandmalish\.node-gyp\12.2.0\include\node\v8.h(3412): note: see declaration of 'v8::Object::
  Get' (compiling source file ..\src\index.cc)
c:\kassmaster\node_modules\nan\nan.h(1842): warning C4996: 'v8::Object::Get': was declared deprecated (co
mpiling source file ..\src\index.cc) [C:\KassMaster\node_modules\node-atol-wrapper\build\node_atol_wrappe
r.vcxproj]
  c:\users\didiandmalish\.node-gyp\12.2.0\include\node\v8.h(3412): note: see declaration of 'v8::Object::
  Get' (compiling source file ..\src\index.cc)
c:\kassmaster\node_modules\nan\nan.h(1847): warning C4996: 'v8::Object::Get': was declared deprecated (co
mpiling source file ..\src\index.cc) [C:\KassMaster\node_modules\node-atol-wrapper\build\node_atol_wrappe
r.vcxproj]
  c:\users\didiandmalish\.node-gyp\12.2.0\include\node\v8.h(3416): note: see declaration of 'v8::Object::
  Get' (compiling source file ..\src\index.cc)
c:\kassmaster\node_modules\nan\nan.h(1818): warning C4996: 'v8::Object::Set': was declared deprecated (co
mpiling source file ..\src\fptr10.cc)c:\kassmaster\node_modules\nan\nan_object_wrap.h(24): error C2039: '
IsNearDeath': is not a member of 'Nan::Persistent<v8::Object,v8::NonCopyablePersistentTraits<T>>' [C:\Kas
sMaster\node_modules\node-atol-wrapper\build\node_atol_wrapper.vcxproj]
          with
          [
              T=v8::Object
          ] (compiling source file ..\src\index.cc)
  c:\users\didiandmalish\.node-gyp\12.2.0\include\node\v8.h(3358): note: see declaration of 'v8::Object::
  Set' (compiling source file ..\src\fptr10.cc)
c:\kassmaster\node_modules\nan\nan.h(1824): warning C4996: 'v8::Object::Set': was declared deprecated (co
mpiling source file ..\src\fptr10.cc) [C:\KassMaster\node_modules\node-atol-wrapper\build\node_atol_wrapp
er.vcxproj]

  c:\users\didiandmalish\.node-gyp\12.2.0\include\node\v8.h(3358): note: see declaration of 'v8::Object::
  Set' (compiling source file ..\src\fptr10.cc)
c:\kassmaster\node_modules\nan\nan.h(1830): warning C4996: 'v8::Object::Set': was declared deprecated (co
mpiling source file ..\src\fptr10.cc) [C:\KassMaster\node_modules\node-atol-wrapper\build\node_atol_wrapp
er.vcxproj]
  c:\users\didiandmalish\.node-gyp\12.2.0\include\node\v8.h(3367): note: see declaration of 'v8::Object::
  Set' (compiling source file ..\src\fptr10.cc)
c:\kassmaster\node_modules\nan\nan.h(1836): warning C4996: 'v8::Object::Get': was declared deprecated (co
mpiling source file ..\src\fptr10.cc) [C:\KassMaster\node_modules\node-atol-wrapper\build\node_atol_wrapp
er.vcxproj]
  c:\users\didiandmalish\.node-gyp\12.2.0\include\node\v8.h(3412): note: see declaration of 'v8::Object::
  Get' (compiling source file ..\src\fptr10.cc)
c:\kassmaster\node_modules\nan\nan.h(1842): warning C4996: 'v8::Object::Get': was declared deprecated (co
mpiling source file ..\src\fptr10.cc) [C:\KassMaster\node_modules\node-atol-wrapper\build\node_atol_wrapp
er.vcxproj]
  c:\users\didiandmalish\.node-gyp\12.2.0\include\node\v8.h(3412): note: see declaration of 'v8::Object::
  Get' (compiling source file ..\src\fptr10.cc)
c:\kassmaster\node_modules\nan\nan.h(1847): warning C4996: 'v8::Object::Get': was declared deprecated (co
mpiling source file ..\src\fptr10.cc) [C:\KassMaster\node_modules\node-atol-wrapper\build\node_atol_wrapp
er.vcxproj]
  c:\users\didiandmalish\.node-gyp\12.2.0\include\node\v8.h(3416): note: see declaration of 'v8::Object::
  Get' (compiling source file ..\src\fptr10.cc)
  c:\kassmaster\node_modules\nan\nan.h(1859): note: see declaration of 'Nan::Persistent<v8::Object,v8::No
  nCopyablePersistentTraits<T>>'
          with
          [
              T=v8::Object
          ] (compiling source file ..\src\index.cc)c:\kassmaster\node_modules\nan\nan_object_wrap.h(24):
  error C2039: 'IsNearDeath': is not a member of 'Nan::Persistent<v8::Object,v8::NonCopyablePersistentTra
  its<T>>'
          with
          [
              T=v8::Object
          ] (compiling source file ..\src\fptr10.cc)

c:\kassmaster\node_modules\nan\nan_object_wrap.h(67): warning C4996: 'v8::PersistentBase<v8::Object>::Mar
kIndependent': was declared deprecated (compiling source file ..\src\index.cc)c:\kassmaster\node_modules\
nan\nan.h(1859): note: see declaration of 'Nan::Persistent<v8::Object,v8::NonCopyablePersistentTraits<T>>
' [C:\KassMaster\node_modules\node-atol-wrapper\build\node_atol_wrapper.vcxproj]
          with
          [
              T=v8::Object
          ] (compiling source file ..\src\fptr10.cc)

  c:\users\didiandmalish\.node-gyp\12.2.0\include\node\v8.h(563): note: see declaration of 'v8::Persisten
  tBase<v8::Object>::MarkIndependent' (compiling source file ..\src\index.cc)c:\kassmaster\node_modules\n
  an\nan_object_wrap.h(67): warning C4996: 'v8::PersistentBase<v8::Object>::MarkIndependent': was declare
  d deprecated (compiling source file ..\src\fptr10.cc)

c:\kassmaster\node_modules\nan\nan_object_wrap.h(124): error C2039: 'IsNearDeath': is not a member of 'Na
n::Persistent<v8::Object,v8::NonCopyablePersistentTraits<T>>' [C:\KassMaster\node_modules\node-atol-wrapp
er\build\node_atol_wrapper.vcxproj]
          with
          [
              T=v8::Object
          ] (compiling source file ..\src\index.cc)c:\users\didiandmalish\.node-gyp\12.2.0\include\node\v
  8.h(563): note: see declaration of 'v8::PersistentBase<v8::Object>::MarkIndependent' (compiling source
  file ..\src\fptr10.cc)

  c:\kassmaster\node_modules\nan\nan.h(1859): note: see declaration of 'Nan::Persistent<v8::Object,v8::No
  nCopyablePersistentTraits<T>>'
          with
          [
              T=v8::Object
          ] (compiling source file ..\src\index.cc)
c:\kassmaster\node_modules\nan\nan_object_wrap.h(124): error C2039: 'IsNearDeath': is not a member of 'Na
n::Persistent<v8::Object,v8::NonCopyablePersistentTraits<T>>' [C:\KassMaster\node_modules\node-atol-wrapp
er\build\node_atol_wrapper.vcxproj]
          with
          [
              T=v8::Object
          ] (compiling source file ..\src\fptr10.cc)
  c:\kassmaster\node_modules\nan\nan.h(1859): note: see declaration of 'Nan::Persistent<v8::Object,v8::No
  nCopyablePersistentTraits<T>>'
          with
          [
              T=v8::Object
          ] (compiling source file ..\src\fptr10.cc)
c:\kassmaster\node_modules\node-atol-wrapper\src\fptr10.cc(26): error C2660: 'v8::FunctionTemplate::GetFu
nction': function does not take 0 arguments [C:\KassMaster\node_modules\node-atol-wrapper\build\node_atol
_wrapper.vcxproj]
  c:\users\didiandmalish\.node-gyp\12.2.0\include\node\v8.h(5947): note: see declaration of 'v8::Function
  Template::GetFunction' (compiling source file ..\src\fptr10.cc)
c:\kassmaster\node_modules\node-atol-wrapper\src\fptr10.cc(26): error C2661: 'v8::Object::Set': no overlo
aded function takes 1 arguments [C:\KassMaster\node_modules\node-atol-wrapper\build\node_atol_wrapper.vcx
proj]
c:\kassmaster\node_modules\node-atol-wrapper\src\fptr10.cc(61): error C2660: 'v8::Value::NumberValue': fu
nction does not take 0 arguments [C:\KassMaster\node_modules\node-atol-wrapper\build\node_atol_wrapper.vc
xproj]
  c:\users\didiandmalish\.node-gyp\12.2.0\include\node\v8.h(2564): note: see declaration of 'v8::Value::N
  umberValue' (compiling source file ..\src\fptr10.cc)
c:\kassmaster\node_modules\node-atol-wrapper\src\fptr10.cc(110): error C2661: 'v8::Value::ToObject': no o
verloaded function takes 0 arguments [C:\KassMaster\node_modules\node-atol-wrapper\build\node_atol_wrappe
r.vcxproj]
c:\kassmaster\node_modules\node-atol-wrapper\src\fptr10.cc(156): error C2661: 'v8::Value::ToObject': no o
verloaded function takes 0 arguments [C:\KassMaster\node_modules\node-atol-wrapper\build\node_atol_wrappe
r.vcxproj]
  utils.cc
  win_delay_load_hook.cc
c:\kassmaster\node_modules\nan\nan_converters_43_inl.h(22): warning C4996: 'v8::Value::ToBoolean': was de
clared deprecated (compiling source file ..\src\utils.cc) [C:\KassMaster\node_modules\node-atol-wrapper\b
uild\node_atol_wrapper.vcxproj]
  c:\users\didiandmalish\.node-gyp\12.2.0\include\node\v8.h(2523): note: see declaration of 'v8::Value::T
  oBoolean' (compiling source file ..\src\utils.cc)
c:\kassmaster\node_modules\nan\nan_converters_43_inl.h(40): warning C4996: 'v8::Value::BooleanValue': was
 declared deprecated (compiling source file ..\src\utils.cc) [C:\KassMaster\node_modules\node-atol-wrappe
r\build\node_atol_wrapper.vcxproj]
  c:\users\didiandmalish\.node-gyp\12.2.0\include\node\v8.h(2561): note: see declaration of 'v8::Value::B
  ooleanValue' (compiling source file ..\src\utils.cc)
c:\kassmaster\node_modules\nan\nan_implementation_12_inl.h(103): error C2664: 'v8::MaybeLocal<v8::Functio
n> v8::Function::New(v8::Local<v8::Context>,v8::FunctionCallback,v8::Local<v8::Value>,int,v8::Constructor
Behavior,v8::SideEffectType)': cannot convert argument 1 from 'v8::Isolate *' to 'v8::Local<v8::Context>'
 (compiling source file ..\src\utils.cc) [C:\KassMaster\node_modules\node-atol-wrapper\build\node_atol_wr
apper.vcxproj]
  c:\kassmaster\node_modules\nan\nan_implementation_12_inl.h(105): note: No constructor could take the so
  urce type, or constructor overload resolution was ambiguous (compiling source file ..\src\utils.cc)
c:\kassmaster\node_modules\nan\nan_implementation_12_inl.h(337): error C2660: 'v8::StringObject::New': fu
nction does not take 1 arguments (compiling source file ..\src\utils.cc) [C:\KassMaster\node_modules\node
-atol-wrapper\build\node_atol_wrapper.vcxproj]
  c:\users\didiandmalish\.node-gyp\12.2.0\include\node\v8.h(5380): note: see declaration of 'v8::StringOb
  ject::New' (compiling source file ..\src\utils.cc)
c:\kassmaster\node_modules\nan\nan_implementation_12_inl.h(337): error C2059: syntax error: ')' (compilin
g source file ..\src\utils.cc) [C:\KassMaster\node_modules\node-atol-wrapper\build\node_atol_wrapper.vcxp
roj]
c:\kassmaster\node_modules\nan\nan.h(1034): error C2661: 'v8::Value::ToString': no overloaded function ta
kes 0 arguments (compiling source file ..\src\utils.cc) [C:\KassMaster\node_modules\node-atol-wrapper\bui
ld\node_atol_wrapper.vcxproj]
c:\kassmaster\node_modules\nan\nan.h(1044): error C2664: 'int v8::String::WriteUtf8(v8::Isolate *,char *,
int,int *,int) const': cannot convert argument 1 from 'char *' to 'v8::Isolate *' (compiling source file 
..\src\utils.cc) [C:\KassMaster\node_modules\node-atol-wrapper\build\node_atol_wrapper.vcxproj]
  c:\kassmaster\node_modules\nan\nan.h(1044): note: Types pointed to are unrelated; conversion requires r
  einterpret_cast, C-style cast or function-style cast (compiling source file ..\src\utils.cc)
c:\kassmaster\node_modules\nan\nan.h(1818): warning C4996: 'v8::Object::Set': was declared deprecated (co
mpiling source file ..\src\utils.cc) [C:\KassMaster\node_modules\node-atol-wrapper\build\node_atol_wrappe
r.vcxproj]
  c:\users\didiandmalish\.node-gyp\12.2.0\include\node\v8.h(3358): note: see declaration of 'v8::Object::
  Set' (compiling source file ..\src\utils.cc)
c:\kassmaster\node_modules\nan\nan.h(1824): warning C4996: 'v8::Object::Set': was declared deprecated (co
mpiling source file ..\src\utils.cc) [C:\KassMaster\node_modules\node-atol-wrapper\build\node_atol_wrappe
r.vcxproj]
  c:\users\didiandmalish\.node-gyp\12.2.0\include\node\v8.h(3358): note: see declaration of 'v8::Object::
  Set' (compiling source file ..\src\utils.cc)
c:\kassmaster\node_modules\nan\nan.h(1830): warning C4996: 'v8::Object::Set': was declared deprecated (co
mpiling source file ..\src\utils.cc) [C:\KassMaster\node_modules\node-atol-wrapper\build\node_atol_wrappe
r.vcxproj]
  c:\users\didiandmalish\.node-gyp\12.2.0\include\node\v8.h(3367): note: see declaration of 'v8::Object::
  Set' (compiling source file ..\src\utils.cc)
c:\kassmaster\node_modules\nan\nan.h(1836): warning C4996: 'v8::Object::Get': was declared deprecated (co
mpiling source file ..\src\utils.cc) [C:\KassMaster\node_modules\node-atol-wrapper\build\node_atol_wrappe
r.vcxproj]
  c:\users\didiandmalish\.node-gyp\12.2.0\include\node\v8.h(3412): note: see declaration of 'v8::Object::
  Get' (compiling source file ..\src\utils.cc)
c:\kassmaster\node_modules\nan\nan.h(1842): warning C4996: 'v8::Object::Get': was declared deprecated (co
mpiling source file ..\src\utils.cc) [C:\KassMaster\node_modules\node-atol-wrapper\build\node_atol_wrappe
r.vcxproj]
  c:\users\didiandmalish\.node-gyp\12.2.0\include\node\v8.h(3412): note: see declaration of 'v8::Object::
  Get' (compiling source file ..\src\utils.cc)
c:\kassmaster\node_modules\nan\nan.h(1847): warning C4996: 'v8::Object::Get': was declared deprecated (co
mpiling source file ..\src\utils.cc) [C:\KassMaster\node_modules\node-atol-wrapper\build\node_atol_wrappe
r.vcxproj]
  c:\users\didiandmalish\.node-gyp\12.2.0\include\node\v8.h(3416): note: see declaration of 'v8::Object::
  Get' (compiling source file ..\src\utils.cc)
c:\kassmaster\node_modules\nan\nan_object_wrap.h(24): error C2039: 'IsNearDeath': is not a member of 'Nan
::Persistent<v8::Object,v8::NonCopyablePersistentTraits<T>>' [C:\KassMaster\node_modules\node-atol-wrappe
r\build\node_atol_wrapper.vcxproj]
          with
          [
              T=v8::Object
          ] (compiling source file ..\src\utils.cc)
  c:\kassmaster\node_modules\nan\nan.h(1859): note: see declaration of 'Nan::Persistent<v8::Object,v8::No
  nCopyablePersistentTraits<T>>'
          with
          [
              T=v8::Object
          ] (compiling source file ..\src\utils.cc)
c:\kassmaster\node_modules\nan\nan_object_wrap.h(67): warning C4996: 'v8::PersistentBase<v8::Object>::Mar
kIndependent': was declared deprecated (compiling source file ..\src\utils.cc) [C:\KassMaster\node_module
s\node-atol-wrapper\build\node_atol_wrapper.vcxproj]
  c:\users\didiandmalish\.node-gyp\12.2.0\include\node\v8.h(563): note: see declaration of 'v8::Persisten
  tBase<v8::Object>::MarkIndependent' (compiling source file ..\src\utils.cc)
c:\kassmaster\node_modules\nan\nan_object_wrap.h(124): error C2039: 'IsNearDeath': is not a member of 'Na
n::Persistent<v8::Object,v8::NonCopyablePersistentTraits<T>>' [C:\KassMaster\node_modules\node-atol-wrapp
er\build\node_atol_wrapper.vcxproj]
          with
          [
              T=v8::Object
          ] (compiling source file ..\src\utils.cc)
  c:\kassmaster\node_modules\nan\nan.h(1859): note: see declaration of 'Nan::Persistent<v8::Object,v8::No
  nCopyablePersistentTraits<T>>'
          with
          [
              T=v8::Object
          ] (compiling source file ..\src\utils.cc)
c:\kassmaster\node_modules\node-atol-wrapper\src\utils.cc(31): error C2661: 'v8::Value::ToObject': no ove
rloaded function takes 0 arguments [C:\KassMaster\node_modules\node-atol-wrapper\build\node_atol_wrapper.
vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:196:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:257:12)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\KassMaster\node_modules\node-atol-wrapper
gyp ERR! node -v v12.2.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN kass-master@0.0.1 No repository field.
npm WARN kass-master@0.0.1 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-atol-wrapper@0.0.13 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-atol-wrapper@0.0.13 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\didiandmalish\AppData\Roaming\npm-cache\_logs\2019-05-15T10_52_10_105Z-debug.log

**Comment by squalsoft** [comment]
Видимо, нужна какая-то более старая версия node. На какой версии следует компилировать?

**Comment by squalsoft** [comment]
Методом тыка удалось установить данный пакет (и скомпилировать необходимые файлы при установке) в версии node v8.11.0.
